default: &default
    adapter: postgresql
    pool: 5
    timeout: 5000
    host: taskerPostgres
    user: tasker
    password: tasker

development:
    <<: *default
    database: tasker_development

test:
  <<: *default
  database: tasker_test

production:
  <<: *default
  database: tasker_production
